# Generated by Django 4.1.4 on 2023-01-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Blaggers', max_length=200),
        ),
    ]
